### ISSUE TITLE
[docs] Build the documentation website

### ISSUE THREAD

**Issue by yannduran** [luminous-software/start-page-plus-64-bit#31]
```[tasklist]
### Tasks
- [ ] README.md (github)
- [ ] marketplace.md (marketplace)
- [ ] index.md (website)
- [ ] known-issues.md (website)
- [ ] features.md (website)
```
